version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: compile
          command: make
      - run:
          name: run
          command: ./anc
