version: 2
jobs:
  build:
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - run:
          name: compile
          command: make
      - run:
          name: run
          command: ./anc
      - run:
          name: upload
          command: bash <(curl -s https://codecov.io/bash)
